"""Upload the dealership's props to Roblox, and write the table the game places them from.

    python sandbox/dealership/props/upload.py              upload any not yet uploaded, then write
    python sandbox/dealership/props/upload.py --write-only just write the table from manifest.json

Each downloaded .glb (textures already capped at 1024 px by Sketchfab) goes up through Open Cloud's
Assets API as a Model owned by the user, with its creator's credit in the description -- the CC
Attribution licence asks for that. The asset id is recorded in manifest.json, and
src/server/content/DealershipProps.luau is rewritten from the manifest: what DealershipDressing
reads to swap each block stand-in for its model.

The API key is read from the ROBLOX_API_KEY user environment variable, which the user sets
themselves. It is sent only as the x-api-key header to apis.roblox.com and never printed, logged
or written anywhere.
"""

import json
import os
import pathlib
import sys
import time
import urllib.error
import urllib.request
import uuid

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent
MANIFEST = HERE / "manifest.json"
LUAU = ROOT / "src/server/content/DealershipProps.luau"
USER_ID = "7771953740"  # DARKLIGHT0773
ASSETS = "https://apis.roblox.com/assets/v1"
MAX_BYTES = 20_000_000


def api_key() -> str:
    key = os.environ.get("ROBLOX_API_KEY")
    if not key and sys.platform == "win32":
        import winreg

        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, "Environment") as reg:
                key = winreg.QueryValueEx(reg, "ROBLOX_API_KEY")[0]
        except OSError:
            key = None
    if not key:
        sys.exit("ROBLOX_API_KEY is not set. Create an Open Cloud key with Assets read + write and save it as that user environment variable.")
    return key


def request(method: str, url: str, key: str, body: bytes | None = None, content_type: str | None = None) -> dict:
    req = urllib.request.Request(url, data=body, method=method)
    req.add_header("x-api-key", key)
    if content_type:
        req.add_header("Content-Type", content_type)
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read() or b"{}")
    except urllib.error.HTTPError as e:
        detail = e.read().decode("utf-8", "replace")[:600]
        raise RuntimeError(f"{method} {url.split('?')[0]} -> HTTP {e.code}: {detail}") from None


def upload(entry: dict, key: str) -> str:
    path = HERE / "downloads" / f"{entry['key']}.glb"
    data = path.read_bytes()
    if len(data) > MAX_BYTES:
        raise RuntimeError(f"{path.name} is {len(data)} bytes, over Open Cloud's 20 MB limit")
    meta = {
        "assetType": "Model",
        "displayName": f"Meridian {entry['key']}"[:50],
        "description": f"{entry['name']} by {entry['author']} ({entry['license']}), {entry['url']}"[:1000],
        "creationContext": {"creator": {"userId": USER_ID}},
    }
    boundary = uuid.uuid4().hex
    parts = [
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"request\"\r\nContent-Type: application/json\r\n\r\n".encode(),
        json.dumps(meta).encode(),
        f"\r\n--{boundary}\r\nContent-Disposition: form-data; name=\"fileContent\"; filename=\"{path.name}\"\r\nContent-Type: model/gltf-binary\r\n\r\n".encode(),
        data,
        f"\r\n--{boundary}--\r\n".encode(),
    ]
    op = request("POST", f"{ASSETS}/assets", key, b"".join(parts), f"multipart/form-data; boundary={boundary}")
    op_id = op.get("operationId") or op.get("path", "").split("/")[-1]
    for _ in range(90):
        if op.get("done"):
            break
        time.sleep(2)
        op = request("GET", f"{ASSETS}/operations/{op_id}", key)
    if not op.get("done"):
        raise RuntimeError(f"{entry['key']}: upload still processing after 3 minutes (operation {op_id}); run again later")
    if "error" in op:
        raise RuntimeError(f"{entry['key']}: {op['error']}")
    return str(op["response"]["assetId"])


def luau_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_luau(entries: list) -> None:
    lines = [
        "--!strict",
        "-- The dealership's props: Sketchfab models that stand in for the builder's block versions.",
        "-- GENERATED by sandbox/dealership/props/upload.py from sandbox/dealership/props/manifest.json --",
        "-- edit the manifest and rerun it, not this file.",
        "--",
        "-- Each is under CC Attribution; the credit is here and in sandbox/dealership/props/CREDITS.md.",
        "-- A prop with no assetId has not been uploaded yet, and its stand-in simply stays.",
        "--",
        '-- fit: "height" matches the stand-in\'s height, "width" its length across its facing,',
        '-- "footprint" the largest fit inside its plan. yaw turns the model so its front faces local',
        "-- -Z, the builder's front. variants are sets of part names, one set per stand-in by its",
        "-- Variant attribute (a pack of three trees gives three trees); drop removes parts by name.",
        "",
        "export type Prop = {",
        "\tkey: string,",
        "\tname: string,",
        "\tauthor: string,",
        "\tlicense: string,",
        "\turl: string,",
        "\tassetId: number?,",
        '\tfit: "height" | "width" | "footprint",',
        "\tyaw: number,",
        "\tcollide: boolean,",
        "\tdrop: { string },",
        "\tvariants: { { string } },",
        "}",
        "",
        "local DealershipProps: { [string]: Prop } = {",
    ]
    for e in entries:
        names = lambda xs: "{ " + ", ".join(luau_string(x) for x in xs) + " }" if xs else "{}"
        variants = "{ " + ", ".join(names(v) for v in e["variants"]) + " }" if e["variants"] else "{}"
        asset = e.get("robloxAssetId")
        lines += [
            f"\t{e['key']} = {{",
            f"\t\tkey = {luau_string(e['key'])},",
            f"\t\tname = {luau_string(e['name'])},",
            f"\t\tauthor = {luau_string(e['author'])},",
            f"\t\tlicense = {luau_string(e['license'])},",
            f"\t\turl = {luau_string(e['url'])},",
            f"\t\tassetId = {asset if asset else 'nil'},",
            f"\t\tfit = {luau_string(e['fit'])},",
            f"\t\tyaw = {e['yaw']},",
            f"\t\tcollide = {'true' if e['collide'] else 'false'},",
            f"\t\tdrop = {names(e['drop'])},",
            f"\t\tvariants = {variants},",
            "\t},",
        ]
    lines += ["}", "", "return DealershipProps", ""]
    LUAU.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    entries = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if "--write-only" not in sys.argv:
        key = api_key()
        for e in entries:
            if e.get("robloxAssetId") or not e.get("downloaded"):
                continue
            print(f"  uploading {e['key']} ...", flush=True)
            try:
                e["robloxAssetId"] = upload(e, key)
                print(f"    asset {e['robloxAssetId']}")
            except RuntimeError as err:
                print(f"    FAILED: {err}")
            MANIFEST.write_text(json.dumps(entries, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    write_luau(entries)
    done = sum(1 for e in entries if e.get("robloxAssetId"))
    print(f"  wrote {LUAU.relative_to(ROOT)}: {done} of {len(entries)} props uploaded")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
